# Supabase Project Configuration
project_id = "pudncilureqpzxrxfupr"

# API Configuration
[api]
  # Port for the API URL
  port = 54321
  # Schemas to expose in your API
  schemas = ["fivetran_views", "storage"]
  # Extra schemas to add to the search_path of every request
  extra_search_path = ["fivetran_views", "extensions"]
  # Max rows to return from a view, table, or stored procedure
  max_rows = 1000

# Database Configuration
[db]
  # Port for the database URL
  port = 5432

# Edge Functions Configuration
[functions]
  serve = { port = 54321 }