// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://pudncilureqpzxrxfupr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "";

// Type augmentation for the execute_sql_query RPC function
declare module '@supabase/supabase-js' {
  interface SupabaseClient<Database> {
    rpc(
      fn: 'execute_sql_query' | 'get_weekly_lead_counts' | 'query_salesforce_lead' | string,
      params?: Record<string, any>
    ): any;
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create the Supabase client with specific options for headers
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        // Include necessary headers that might be required for cross-schema access
        'x-client-info': 'primer-analytics-dashboard'
      },
    },
    db: {
      schema: 'public',
    },
  }
);

// Helper function to check database connectivity to both public and salesforce schemas
export const checkDatabaseConnection = async () => {
  try {
    // First check public schema access
    const publicCheck = await supabase
      .from('campuses')
      .select('count')
      .limit(1);
    
    if (publicCheck.error) {
      console.error("Public schema connectivity check failed:", publicCheck.error);
      return { connected: false, schemas: { public: false, salesforce: false }};
    }
    
    // Then check salesforce schema access
    let salesforceAccess = false;
    try {
      // Use an RPC function that attempts to access the salesforce schema
      const salesforceCheck = await supabase.rpc('test_salesforce_connection');
      salesforceAccess = !salesforceCheck.error && salesforceCheck.data?.salesforce_schema_access === true;
    } catch (schemaError) {
      console.error("Salesforce schema access check failed:", schemaError);
      // Continue even if this fails - we still have public schema access
    }
    
    // Return results
    return { 
      connected: true, 
      schemas: { 
        public: true, 
        salesforce: salesforceAccess 
      }
    };
  } catch (error) {
    console.error("Unexpected error during database connectivity check:", error);
    return { connected: false, schemas: { public: false, salesforce: false }};
  }
};
